### ISSUE TITLE
how to solve this problem that program is killed when I run "CUDA_VISIBLE_DEVICES=0 python finetune.py ucf101 rgb 1" command in the terminal?

### ISSUE THREAD

**Issue by MrCuiHao** [USTC-Video-Understanding/I3D_Finetune#26]
**The error infomation is reported as follows:**

root@roronoa:~/AI/action_recognition/I3D_Finetune# CUDA_VISIBLE_DEVICES=0 python finetune.py ucf101 rgb 1
2019-03-28 14:58:42.898076: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
INFO:tensorflow:Restoring parameters from ./data/checkpoints/rgb_imagenet/model.ckpt
----Here we start!----
Output wirtes to output/finetune-ucf101-rgb-1
已杀死

**pelease allow me submit three questions:**
**Firstly**, I have a GPU named "GeForce GTX 1080" with 8GB size of memory , Is enough to process these frames?
**Secondly**, when I run "CUDA_VISIBLE_DEVICES=0 python finetune.py ucf101 rgb 1" command in terminal , but as you can see in the error report , GPU is not used , why?
**Finally**, why the program is killed in the end? Must the "finetune.py" use the GPU?

**Comment by MrCuiHao** [comment]
I have solved this problem，the reason may be that I did't install the correct environment
1、the version of cuda maybe match the kernel of ubuntu
2、cuda maybe match tensorflow
anyway ，you can try to test your repository downloaded by using tensorflow to print gpu info，because  
this repo can't run ,if you use cpu

**Comment by Ronales** [comment]
@MrCuiHao I also encounter this problems,

2020-01-09 18:48:20.593448: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
WARNING:tensorflow:From /media/daniel/D/ycc/Anaconda3/envs/python27/lib/python2.7/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from ./data/checkpoints/rgb_imagenet/model.ckpt
----Here we start!----
Output wirtes to output/finetune-ucf101-rgb-1





Can you tell me your solution?Thanks in advance！
